### ISSUE TITLE
After installing Fritzbox plugin , I see no settings button for this app 

### ISSUE THREAD

**Issue by F3000** [hoobs-org/hoobs-core#12]

**Comment by mkellsy** [comment]
There is now a config link.

**Comment by mkellsy** [comment]
Please note this is pre-beta software. It is not advised to use this. We will notify the public when we are getting ready to release.

[HOOBS website](https://hoobs.org)  
[HOOBS Support Chat](https://m.me/HOOBSofficial)  
[HOOBS email](mailto:info@hoobs.org)  
[HOOBS Subreddit](https://www.reddit.com/r/hoobs/)  
[HOOBS Facebook Page](https://www.facebook.com/HOOBSofficial)  
[HOOBS Facebook Support Group](https://www.facebook.com/groups/HOOBSorg/)
