### ISSUE TITLE
Installing a plugin spams console while homebridge is down

### ISSUE THREAD

**Issue by askovi** [hoobs-org/hoobs-core#19]
![image](https://user-images.githubusercontent.com/3981552/62420539-be29bc80-b661-11e9-80e7-cf362300a544.png)
When installing a plugin from the UI, homebridge shuts down then spams ECONNREFUSED every ms until plugin is installed then homebridge starts again gracefully. 

Proposed fix: Homebridge should not stop while installing the plugin, should restart when plugin finishes installation process.

**Comment by mkellsy** [comment]
This is the accessory polling. Need to not run this is the service is down.

**Comment by mkellsy** [comment]
Accessories don't try to update when the Homebridge service is down. Update is committed.
