### ISSUE TITLE
Add the Ability to Rename Accessories and Store Locally

### ISSUE THREAD

**Issue by BobbySlope** [hoobs-org/hoobs-core#34]
<img width="1497" alt="Bildschirmfoto 2019-08-22 um 06 50 02" src="https://user-images.githubusercontent.com/50763727/63486968-ca0ede80-c4a9-11e9-943b-6ac13cefcac1.png">

**Comment by mkellsy** [comment]
Moved to main repo

**Comment by mkellsy** [comment]
Done in 3.0.0-beta.48
