### ISSUE TITLE
Certify Voice Assistant Plugins

### ISSUE THREAD

**Issue by BobbySlope** [hoobs-org/hoobs-core#47]
move on top and call it system integration or similar

add homekit tile (opens qr-code and scancardium) 
add Alexa tile 

<img width="941" alt="Bildschirmfoto 2019-08-22 um 07 11 09" src="https://user-images.githubusercontent.com/50763727/63487584-28d55780-c4ac-11e9-929c-64f74354657a.png">

**Comment by mkellsy** [comment]
issue moved
