### ISSUE TITLE
IP Address JSON API

### ISSUE THREAD

**Issue by AlexanderBabel** [hoobs-org/hoobs-core#62]
The currently used JSON API to get some meta data from the IP address is not using a HTTPS connection. Please use a service that offers HTTPS. 

Otherwise you'll cannot see weather information if you're using a secure connection.

**Comment by mkellsy** [comment]
We are tracking issues on our HOOBS repo.
Issue merged with https://github.com/hoobs-org/HOOBS/issues/93
