### ISSUE TITLE
Graphical Edits

### ISSUE THREAD

**Issue by BobbySlope** [hoobs-org/hoobs-core#9]
Fonttype Montserrat 
https://fonts.google.com/specimen/Montserrat

H1 Title		25pt	MONTSERRAT Bold H2 
Headline	        20pt	Montserrat Medium
HL Highlight	14pt	Montserrat Medium	
B Bold		12pt	        Montserrat Medium	
P Paragraph	12pt.  	Montserrat Light.
S Subtext	10pt	         Montserrat Light

Logo always with rounded border and HOOBS always written Bold

BOX shadows on Dark Theme must be Harder to be visible clearly

**Comment by mkellsy** [comment]
This is on my to-do list.

Next Steps

1. Wire in the Montserrat font, I will need the regular and bold variants
2. Adjust all text in the interface, new font new sizes.
3. Extract the logo from Ai and convert to simplified SVG and change the header logo.
4. Add logo color to the theme file, it will need to change for dark mode.
5. Bold the HOOBS in the header. This will look cool too.

**Comment by mkellsy** [comment]
I also need to adjust the box shadows in dark mode. The box shadows will need to be moved to the theme file.

**Comment by mkellsy** [comment]
I got this done, just need to create new screenshots.

**Comment by mkellsy** [comment]
This is done
